#Currently only works with PostgreSQL. NoSQL planned for the future
postgresql:
  adress: #0.0.0.0
  port: #5432
  user: #postgres
  password: #123456789
  database: #postgres
#expireRestarts checks for how many restarts a player has been inactive and auto expires their shop.
expireRestarts: 30
allowedShops: 1
